RMS/Controllers/SetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessModel.Setup;
using RMS.Service;

namespace RMS.Controllers
{
    public class SetupController : Controller
    {
        private readonly ISetupServices ser;
        public SetupController()
        {
            ser = new SetupService();
        }
        // GET: Setup
        
        public ActionResult Index()
        {
            SetupModel model = new SetupModel();

            model.list = ser.GetList();

            return View(model);
        }
        

        public ActionResult CreateFlor()
        {
            return View();
        }

        public ActionResult CreateRent()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(SetupModel model)
        {
            SetupModel model1 = new SetupModel();
            
            model1 = ser.Create(model);
            model1.list = ser.GetList();
            return View("Index",model1);
        }

        public ActionResult Edit(int? id)
        {
            SetupModel model = new SetupModel();

            model = ser.GetById(id);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(SetupModel model)
        {
            SetupModel model1 = new SetupModel();

            model1 = ser.Edit(model);
            model1.list = ser.GetList();

            return View("Index", model1);
        } 

        public ActionResult Delete(int? id)
        {
            return View(ser.GetById(id));
        }

        [HttpPost]
        public ActionResult Delete(SetupModel model)
        {
            model = ser.Delete(model);
            model.list = ser.GetList();
            return RedirectToAction("Index",model);
        }


    }
}

RMS/Views/Setup/Create.cshtml
@using BusinessModel.Setup
@model SetupModel



<div>
    <h1>Create Rent Information</h1>
    <form method="post">
        <div class="row form-group">
            <div class="col-md-4">
                <label>FloorId</label>
                <input type="text" name="FloorId"  class="form-control" />
            </div>
            <div class="col-md-4">
                <label>Amount</label>
                <input type="number" name="Amount"  class="form-control" />
            </div>
        </div>
        <div>
            <input type="submit" value="Create" class="btn btn-success" />
            <a href="/Setup/Index" class="btn btn-primary">Back</a>
        </div>
    </form>
</div>

RMS/Views/Setup/Delete.cshtml
@using BusinessModel.Setup
@model SetupModel

<div>
    <p><font size="5" color="Red">Do you wan to delete Following Family Info ?</font> </p>
    <table class=" table table-bordered table-content table-hover" style="font-family:'Comic Sans MS'">
        <tr>
            <td>
                <b>FloorID :</b>
            </td>
            <td>
                <b>@Model.FloorId</b>
            </td>

        </tr>
        <tr>
            <td>
                <b>Amount :</b>
            </td>
            <td>
                <b>@Model.Amount</b>
            </td>

        </tr>
   
    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken();

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class=" btn btn-danger" />
            @Html.ActionLink("Cancel", "Index", "Setup", new { @class = "btn btn-primary" })
        </div>
    }
</div>

RMS/Views/Setup/Edit.cshtml
@using BusinessModel.Setup
@model SetupModel

<div>
    <h1>Edit Information</h1>
    <form method="post">
        <div class="row form-group">
            <div class="col-md-4">
                <label>FloorId</label>
                <input type="text" name="FloorId" value="@Model.FloorId" class="form-control" />
            </div>
            <div class="col-md-4">
                <label>Amount</label>
                <input type="number"  name="Amount" value="@Model.Amount" class="form-control" />
            </div>
        </div>
        <div>
            <input type="submit" value="Update" class="btn btn-success" />
            <a href="/Setup/Index" class="btn btn-primary">Back</a>
        </div>
    </form>
</div>

RMS/Views/Setup/Index.cshtml
@using BusinessModel.Setup
@model SetupModel

@if (Model.IsSuccess)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>@Model.SuccessMessage</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

@if (!Model.IsSuccess && Model.flag == 1)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>@Model.SuccessMessage</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="table-responsive">
    <h1>Rent Floor Wise</h1>
    <a href="/Setup/Create" class="btn btn-primary">Create New</a>
    <table class=" table table-bordered tab-content table-hover">
        <thead>
            <tr>
                <th>FloorId</th>
                <th>Amount</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.list)
            {
                <tr class="info">
                    <td>@item.FloorId</td>
                    <td>@item.Amount</td>
                    <td>
                    <a href="/Setup/Edit/@item.Id" class="btn btn-primary">Update</a>
                    <a href="/Setup/Delete/@item.Id" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>