RMS/Controllers/FamilyInfoController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using RMS.Models;
using RMS.Service.TenantInfo;
using BusinessModel.FamilyInfo;

namespace RMS.Controllers
{
    public class FamilyInfoController : Controller
    {
        private string connString = ConfigurationManager.ConnectionStrings["DBstring"].ToString();

        private readonly IFamilyInfoService ser;

        public FamilyInfoController()
        {
            ser = new FamilyInfoService();
        }
        public ActionResult Index(int? id)
        {
            ViewBag.Id = id;
            if (id == null)
            {
                FamilyInfoModel model = new FamilyInfoModel();
                model.List = ser.GetList();
                return View(model);
            }

            else
            {
                FamilyInfoModel model = new FamilyInfoModel();
                model.List = ser.FamilyList(id);
                return View(model);
            }
        }
        public ActionResult Create(int? id)
        {

            FamilyInfoModel model = new FamilyInfoModel();

            model = ser.Create(id);
            ViewBag.Name = model.FirstName;
            // ViewBag.Id = id;
            ViewBag.Floor = model.FloorId;

            return View();
        }

        [HttpPost]
        public ActionResult Create(FamilyInfoModel model)
        {
            var model2 = new FamilyInfoModel();
            model2 = ser.Create(model);
            model2.List = ser.GetList();
            return View("Index", model2);
        }


        public ActionResult Edit(int? id)
        {

            return View(ser.GetById(id));
        }

        [HttpPost]
        public ActionResult Edit(FamilyInfoModel model)
        {
            var model2 = new FamilyInfoModel();
            model2 = ser.Edit(model);
            model2.List = ser.GetList();
            return View("Index", model2);
        }

        public ActionResult Delete(int? id)
        {
            return View(ser.GetById(id));
        }

        [HttpPost]
        public ActionResult Delete(FamilyInfoModel model)
        {
            var model2 = new FamilyInfoModel();
            model2 = ser.Delete(model);
            model2.List = ser.GetList();

            return View("Index", model2);
        }

    }
}

RMS/Views/Familyinfo/Create.cshtml
@using BusinessModel.FamilyInfo
@model FamilyInfoModel


<div>
    <form method="post">

        <label>Tenant Name: </label>
        <input type="text" disabled name="FullName" value=@ViewBag.Name class="form-control" />
        @*<input type="hidden" name="parentId" value="@ViewBag.Id" class="form-control" />*@
        <label>Firstname</label><input type="text" name="FirstName" class="form-control" />
        <label>Lastname</label><input type="text" name="LastName" class="form-control" />
        <label>Address</label><input type="text" name="Address" class="form-control" />
        <label>Contact</label><input type="number" name="Contact" class="form-control"/>
        <label>gender</label><input type="text" name="gender" class="form-control"/>
        <label>Relationship</label><input type="text" name="Relationship" class="form-control" />
        <label>Date of Birht</label><input type="text" name="Dob" class="form-control" />
        <label>FloorId</label><input type="number" disabled name="FloorId" value="@ViewBag.Floor" class="form-control" />
        

        @*<input type="hidden" value="1" name="Id" />*@

        <div>
            <input type="submit" value="Create" class=" btn btn-success" />

            @Html.ActionLink("Back", "Index", "FamilyInfo", new { @class = "btn btn-primary" })

        </div>
    </form>
</div>

RMS/Views/Familyinfo/Delete.cshtml
@using BusinessModel.FamilyInfo
@model FamilyInfoModel

<div>
    <p><font size="5" color="Red">Do you wan to delete Following Family Info ?</font> </p>
    <table class=" table table-bordered table-content table-hover" style="font-family:'Comic Sans MS'">
        <tr>
            <td>
                <b>FirstName:</b>
            </td>
            <td>
                <b>@Model.FirstName</b>
            </td>

        </tr>
        <tr>
            <td>
                <b>LastName:</b>
            </td>
            <td>
                <b>@Model.LastName</b>
            </td>

        </tr>
        <tr>
            <td>
                <b>Address:</b>
            </td>
            <td>
                <b>@Model.Address</b>
            </td>

        </tr>
        <tr>
            <td>
                <b>Contact:</b>
            </td>
            <td>
                <b>@Model.Contact</b>
            </td>

        </tr>
    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken();

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class=" btn btn-danger" />
            @Html.ActionLink("Cancel", "Index", "FamilyInfo", new { @class = "btn btn-primary" })
        </div>
    }
</div>

RMS/Views/Familyinfo/Edit.cshtml
@using BusinessModel.FamilyInfo
@model FamilyInfoModel

<form method="post">
    <label>Firstname</label><input type="text" name="FirstName" value="@Model.FirstName" class="form-control" />
    <label>Lastname</label><input type="text" name="LastName" value="@Model.LastName" class="form-control" />
    <label>Addressname</label><input type="text" name="Address" value="@Model.Address" class="form-control" />
    <label>Contact</label><input type="number" name="Contact" value="@Model.Contact" class="form-control" />
    <label>gender</label><input type="text" name="gender" value="@Model.gender" class="form-control" />
    <label>Relationship</label><input type="text" name="Relationship" value="@Model.Realtionship" class="form-control" />
    <label>Date of Birth</label><input type="text" name="Dob" value="@Model.Dob" class="form-control" />

    <div>
        <input type="submit" value="Edit" class="btn btn-success" />
        <a href="/TenantInfo/Index" class="btn btn-primary">Cancel</a>
    </div>

</form>

RMS/Views/Familyinfo/Index.cshtml
@using BusinessModel.FamilyInfo
@model FamilyInfoModel


@{
    string FullName = "";



}
<h1>Family Information</h1>
<div class="table-responsive">
    <table class=" table table-bordered table-hover tab-content" id="myTable">
        <thead>
            <tr class="danger">

                <th> Name</th>
                <th> Address</th>
                <th> Contact</th>
                <th>Gender</th>
                <th>Relationship</th>
                <th>Date Of Birth</th> 
                <th> Action</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.List)
            {
                FullName = $" {item.FirstName} {item.LastName}";
                //FullName = item.FirstName + " " + item.LastName;
                //FullName = string.Concat(item.FirstName,item.LastName);



                <tr class="info">

                    <td>@FullName</td>
                    <td>@item.Address</td>
                    <td>@item.Contact</td>
                    <td>@item.Gender</td>
                    <td>@item.Relationship</td>
                    <td>@item.DOB</td>



                    <td>
                        <a href="/FamilyInfo/Edit/@item.Id" class="btn btn-primary" title="Edit"><span class="fa fa-edit"></span></a>
                        <a href="/FamilyInfo/Delete/@item.Id" class="btn btn-danger" title="Delete"><span class="fa fa-trash"></span></a>
                    </td>
                    @*<td>
                            <a href="/Edit/@item.Id" class="btn btn-sm btn-primary"><span class="glyphicon glyphicon-edit"></span></a>
                            <a href="/Delete/@item.Id" class="btn btn-sm btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                        </td>*@

                </tr>


            }
        </tbody>

    </table>
</div>

<p>
    <a href="/FamilyInfo/Create/@ViewBag.Id" class="btn btn-success">Create New</a>
    <a href="/TenantInfo/Index" class="btn btn-primary">Back to main page</a>
</p>